import { ThemeColors } from './colors';

export enum DarkThemeProps {
  TEXT_COLOR = ThemeColors.WHITE,
  GLOW_COLOR = ThemeColors.TRANSLUCENT_VIOLET,
  FOOTER_COLOR = ThemeColors.MEDIUM_GRAY,
  INNER_BACKGROUND = ThemeColors.CHARCOAL,
  INNER_BORDER_COLOR = ThemeColors.LIGHT_GRAY,
  INNER_BOX_SHADOW_INSET = ThemeColors.TRANSLUCENT_VIOLET,
  INNER_BOX_SHADOW_OUTSET = ThemeColors.TRANSLUCENT_WHITE,
  EXPAND_BUTTON_BACKGROUND = ThemeColors.LIGHT_GRAY,
  EXPAND_BUTTON_COLOR = ThemeColors.TRANSLUCENT_VIOLET,
  EXPAND_BUTTON_BORDER_COLOR = ThemeColors.TRANSLUCENT_VIOLET,
  GRADIENT_START_COLOR = ThemeColors.TRANSPARENT,
  GRADIENT_END_COLOR = ThemeColors.OPAQUE_BLACK
}