import { ThemeColors } from './colors';

export enum LightThemeProps {
  TEXT_COLOR = ThemeColors.BLACK,
  GLOW_COLOR = ThemeColors.TRANSLUCENT_NAVY,
  FOOTER_COLOR = ThemeColors.MEDIUM_GRAY,
  INNER_BACKGROUND = ThemeColors.GHOST_WHITE,
  INNER_BORDER_COLOR = ThemeColors.TRANSPARENT,
  INNER_BOX_SHADOW_INSET = ThemeColors.TRANSPARENT,
  INNER_BOX_SHADOW_OUTSET = ThemeColors.TRANSPARENT,
  EXPAND_BUTTON_BACKGROUND = ThemeColors.WHITE,
  EXPAND_BUTTON_COLOR = ThemeColors.TRANSLUCENT_VIOLET,
  EXPAND_BUTTON_BORDER_COLOR = ThemeColors.LIME_GREEN,
  GRADIENT_START_COLOR = ThemeColors.TRANSPARENT,
  GRADIENT_END_COLOR = ThemeColors.OPAQUE_WHITE
}